version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pismo
    network_mode: host

  pismo-api:
    depends_on:
      - "db"
    container_name: pismo-api
    image: mzovico/pismo-api:latest
    ports:
      - '8080:8080'
    network_mode: host